### ISSUE TITLE
OutOfMemoryError on large file download on asBinary

### ISSUE THREAD

**Issue by Catscratch** [OpenUnirest/unirest-java#48]
Hi,

I got a java.lang.OutOfMemoryError when downloading a 2GB zip file with `io.github.openunirest.request.BaseRequest.asBinary`.

Here is the StackTrace:
`
java.lang.OutOfMemoryError: null
    at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
    at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
    at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    at io.github.openunirest.http.utils.ResponseUtils.getBytes(ResponseUtils.java:51)
    at io.github.openunirest.http.utils.ResponseUtils.getRawBody(ResponseUtils.java:85)
    at io.github.openunirest.http.BodyData.<init>(BodyData.java:38)
    at io.github.openunirest.http.BodyData.from(BodyData.java:21)
    at io.github.openunirest.request.ResponseBuilder.asBinary(ResponseBuilder.java:25)
    at io.github.openunirest.request.HttpClientHelper.request(HttpClientHelper.java:34)
    at io.github.openunirest.request.BaseRequest.asBinary(BaseRequest.java:95)
`

Problem is the ByteArrayOutputStream which holds the whole file in memory.

E.g. with Jersey its working. Jersey uses mimepull library.
org.jvnet.mimepull.DataHead$ReadMultiStream

Maybe it would be a nice improvement to use the same? Or any other equivalent?

**Comment by ryber** [comment]
Unirest was originally intended to be a REST client and reads the entire InputStream into memory, even when doing ```.asBinary``` (which is kind of pointless). this is because it wraps Apache HttpClient which needs you to release the connection.

In any case, as stated. As a REST client downloading 2gig files isn't really it's main use case. But I've seen more than you ask about it so I'm going to go ahead and plan on adding a ```.asFile(String fileName)``` method that will stream the response into a file.

In the mean time, you can do this yourself using the new functional methods that operate on the raw response like this:

```
 File r = Unirest.get(MockServer.GET)
                .queryString("foo", "bar")
                .asObject(i -> someMethodThatStreamsInputStreamToFile(i.getContent())
                .getBody();
```

**Comment by ryber** [comment]
Unirest was originally intended to be a REST client and reads the entire InputStream into memory, even when doing ```.asBinary``` (which is kind of pointless). this is because it wraps Apache HttpClient which needs you to release the connection.

In any case, as stated. As a REST client downloading 2gig files isn't really it's main use case. But I've seen more than you ask about it so I'm going to go ahead and plan on adding a ```.asFile(String fileName)``` method that will stream the response into a file.

In the mean time, you can do this yourself using the new functional methods that operate on the raw response like this:

```
 File r = Unirest.get(MockServer.GET)
                .queryString("foo", "bar")
                .asObject(i -> someMethodThatStreamsInputStreamToFile(i.getContent())
                .getBody();
```

**Comment by Catscratch** [comment]
Thanks a lot!

**Comment by ryber** [comment]
Hi @Catscratch 
* Now you can stream the results into a file!
   * It doesn't need to be a file either. It could be any result. Unirest will shove it in a file.
```
File file = Unirest.get("https://someplace/file.tar.gz")
                   .asFile("/local/storage/file.tar.gz")
                   .getBody();
```

Check out 3.2.00 it should be available in maven central in about 20 minutes. If you could test it with your giant file I would appreciate it.

**Comment by Catscratch** [comment]
Tested it. It's working! Thanks!
